---
title: Should I get a PhD (in biostatistics)?
author: ''
date: '2019-03-13'
slug: should-i-get-a-phd-in-biostatistics
categories:
  - '#advice'
tags:
  - '#phd'
  - '#advice'
showDate: true
draft: true
---

During the process of applying to graduate school, I was honestly still unsure about whether getting a PhD was a good idea. So from time to time, I would Google, "should I get a PhD" and see what I find. Chances are, if you're reading this post, you're in a similar boat. Now that I've started my PhD, I have a better idea of whether getting a PhD is a good choice for me. In this post, I'm going to convey what I think would've been useful for me to read back when I was applying.

Before I begin, *please* keep in mind that I am a 2nd year PhD student in biostatistics. This is important because there are vast differences between fields with regard to the PhD experience. I can speak best about the biostatistics program at Johns Hopkins, which likely shares many similarities with other biostatistics programs and, to a lesser extent, other statistics programs. But once you get into other STEM fields (much less non-STEM fields), there are many significant differences that will affect whether a PhD is actually a good idea for you. So just be aware of that as you continue reading.

## 1. Understand Your Trade-Offs

Going to graduate school is far less common than going into college and there's a reason for that. Students often feel burned out and not excited about school by the end of college. Moreover, there are many careers for which a bachelor's degree is all that's required. By going to a PhD program, you are likely going to be trading a career + salary for an apprenticeship + minimum wage. 

To look at this choice from another perspective, if you decide to enter a PhD program, you are essentially committing the next five years to getting a PhD. Therefore, the question you need to ask yourself is, do I want to spend the next stage of my life pursuing a PhD? Will it be a more worthwhile endeavor than working?

Now of course, you might not be able to answer that with a lot of confidence, because no one knows what their PhD experience is going to be like until they do it. However, here are some things you can do to help you form a clearer picture before you even apply: talking to professors in your field, trying research opportunities during undergraduate, and reading blogs like this one. Does it sound like something you also want to do?

## 2. Know What You're Getting Yourself Into

Aside from your personal motivations, there are some important issues outside your control that will also affect whether getting a PhD is worthwhile for you. In particular, there are two questions you should definitely have answered before attending a PhD program.^[You can find the relevant statistics for Johns Hopkins [here](http://oir.jhu.edu/graduate-students/doctoral-students/doctoral-statistics/).]

1. What percent of students successfully complete the program? 
2. How long does it take for the average student to complete the program?

I lucked out in that a high percentage (80-90%?) of entering students for my program graduate in 5 years, but I definitely should have researched this more thoroughly. The reason is that the "PhD horror stories/worst-case scenarios" I hear about most often either concern (1) PhD students getting kicked out of the program or (2) PhD students not being able to graduate after > 7 years. 

Now if you are still in the stage of thinking about graduate school, it might not be so urgent to research this information. But the earlier you can figure this out for yourself, the better, because it might save you the trouble of applying in the first place. I would say just pick an ideal school you can see yourself attending and get a sense of the numbers for their program.

## 3. Everyone is Different

There are a lot of people on the Internet who will caution you against getting a PhD and warn you about all its challenges. I think that's good advice to read for everyone, especially if you're the type of person that's normally very eager. But like all advice (including mine), you should take it with a grain of salt, because everyone is different! 

At least in my case, I would say that reading all those warnings made me feel overly cautious. I never felt like I was **"super passionate"** about statistics, so when someone on the Internet said I should only do a PhD if I can't see myself doing anything else, I thought well... maybe I shouldn't get a PhD after all. 

If I could go back in time and talk to myself, I would say, yes it's important to like your subject (which I know you do), but you don't need to be crazy obsessed^[Honestly, I don't think anyone in my cohort is "crazy obsessed" with statistics.] with it to have a good time! I am living proof of that. Here are some things I enjoy about being a graduate student: 

1. Learning a lot. As an undergraduate, I took a lot of math and statistics classes at a college^[University of Chicago] with well-known programs in both. Even so, there was a lot of new material for me in the required PhD biostatistics curriculum at Johns Hopkins and I felt like I understood a lot of statistical concepts at a deeper level/with a more secure foundation. 

2. All the interesting questions that I get to investigate in research. This is one of the best parts about being in biostatistics -- a lot of medical and scientific questions require statistics, so there's a lot you can do.

3. The flexibility and freedom as a PhD student, i.e. being able to work whenever and wherever I want. 

What I'm saying is, the more you know about how you like to live life, the better able you'll be at measuring other people's advice and gauging whether a PhD program is good for you.

## 4. Take a Chance!

Even if you're still not sure after doing all of the above, if you're considering a PhD program, I would encourage you to take a chance and apply (yes, it will entail that you take the GRE, ask for recommendations, write some essays, and pay application fees). You will likely learn more about whether a PhD program is right for you when you get a chance to interview and talk to the students and professors. 
