---
title: Clearing Out Space in My Macbook
author: ''
date: '2019-12-14'
slug: clearing-out-space-in-my-macbook
categories:
  - advice
tags:
  - mac
  - advice
showDate: no
draft: true
---

Annoying alert that disk space is running low (2-3 GB left of memory!)
Checking mac storage - manage, removed some applications I rarely use (only bought me a few GB). But it unhelpfully tells me that 60GB was in "System." 
To find out what is in System, use utility called Disk Inventory X and discovered some things
I still have old R version 3.4 and 3.5 (a few GB)
the MacTex distribution takes up a lot of space (in addition to the 2016 version, I even still had the old versions 2014, 2015). I replace with Yihui Xie's TinyTex. good experience with blogdown. managing a TeX distribution with R sounds like a good idea. I use TexStudio (had to revert some settings to default) to make it work with the TinyTex distribution.

In total, this saved me about 20 GB. Should be a while before I have to clear out memory again.