---
title: Should You Get a PhD (in biostatistics)?
author: ''
date: '2019-04-25'
slug: should-you-get-a-phd-in-biostatistics
categories:
  - 'advice'
tags:
  - 'phd'
  - 'advice'
showDate: true
draft: false
---

Throughout the process of applying to graduate school, I felt unsure about whether getting a PhD was a good idea. I remember Googling "should I get a PhD" just to see what I could find out of curiosity. Chances are, if you're reading this post, you're in a similar boat. As a now second-year PhD student in biostatistics, I think I have a better idea of whether being in a PhD program has been a good choice for me and I'll share what I think would've been useful for me to know back when I was applying.

## 1. Understand Your Opportunity Cost

By going to a PhD program, you are likely trading a career + salary for an apprenticeship + minimum wage (stipend) for the next 5 years of your life. Therefore, the first question you need to ask yourself is, do I really want to spend the next stage of my life pursuing a PhD? Is it going to be a worthwhile and enjoyable endeavor?

Now of course, you might not be able to answer that with a lot of confidence because no one knows what their PhD experience is going to be like until they do it. However, here are some things you can do to help you form a clearer picture before you even apply: ask professors in your field what they think about getting a PhD, try some research opportunities as an undergraduate, and read blogs by PhD students (like mine!). Does it sound like something you also want to do? Does it seem more appealing than your other life options?

## 2. Understand What You're Getting Yourself Into

Aside from your own personal motivations, there are some important external factors that will have an impact on whether getting a PhD is a good idea. In particular, there are a couple questions you should definitely have answered before attending a PhD program.

1. What is the funding situation for students? 

While having tuition covered and a guaranteed stipend is the norm for biostatistics PhD programs, it's still something you should check. Several PhD programs in other departments at the Johns Hopkins Bloomberg School of Public Health, for instance, cover full tuition but don't guarantee a stipend.

2. What percent of students successfully complete the program? How long does it take for the average student to complete the program?

I lucked out in that a high percentage (~90%?) of entering students for my program are able to successfully graduate in 5 years, but I should have researched this more thoroughly.^[You can find the relevant statistics for Johns Hopkins [here](http://oir.jhu.edu/graduate-students/doctoral-students/doctoral-statistics/).] The reason I say that is because the "PhD horror stories/worst-case scenarios" I hear about most often either concern (1) students getting kicked out of the program or (2) students not being able to graduate after > 7 years. 

3. What are their career prospects?

Hopefully, they're employable. Other than that, you'll want to see that their alumni enter the types of careers that you might also be interested in.^[The PhD alumni placement for Johns Hopkins' biostatistics program is posted [here](http://www.biostat.jhsph.edu/people/alumni/alumphd.shtml).]

## 3. Everyone is Different

There are a lot of people on the Internet who will caution you against getting a PhD. And I do think it's a good idea to keep the numerous challenges in mind and carefully weigh your decision. But with all advice (including mine), you should take it with a grain of salt, because (1) the experience of a PhD student varies a lot by field and (2) everyone is different. At least in my case, I would say that reading all those warnings made me feel overly hesitant. I didn't feel like I was **"super passionate"** about statistics, so when someone on the Internet said I should only do a PhD if I couldn't see myself doing anything else, I thought well... maybe I shouldn't get a PhD.

If I could go back in time and talk to myself, I would say that it's important to like your subject, but you don't need to be crazy obsessed^[Honestly, I wouldn't characterize anyone in my program as being "obsessed" with statistics.] with it to have a good time. Here are some things I've enjoyed about being a PhD student so far: 

1. Learning a lot academically. Even though I was a math/stats double major in college, there was still a lot of new material for me in the required PhD curriculum at Johns Hopkins and I felt like I understood a lot of statistical concepts on a more solid foundation.

2. All the interesting questions that I get to investigate in research. This is one of the best parts about being in biostatistics; since many medical and scientific questions require statistics as part of the solution, there are a lot of options open to you.

3. The freedom and flexibility you have as a PhD student, i.e. being able to work whenever and wherever I want. For the past year, I've rarely had morning commitments so I don't set an alarm to wake up. How many people have that luxury?

What I'm saying is, the more you understand your personality and your desired lifestyle, the better able you'll be at measuring other people's advice relative to yourself and gauging whether a PhD program is right for you. While I personally find much of being a PhD student enjoyable, that may not be the case for everyone.

## Final Thoughts

If you're feeling unsure but you've managed to find this blog post, I would encourage you to take a chance and apply.^[Unfortunately, applying does entail that you do nontrivial tasks like taking the GRE, asking for recommendations, writing some essays, and paying application fees.] The reason I say that is because you will learn more about whether a PhD program is right for you when you get a chance to interview and talk to the students and professors. During my interviews, I got a much better sense of what research in biostatistics and PhD student life is like. It was especially helpful and reassuring to feel like I could see myself as one of the PhD students when I interviewed here at Johns Hopkins and that made me more confident that getting a PhD was a good idea.